// Automatically generated by forge bind-json.

pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {SessionApproval} from "src/v2/authenticators/types/SessionApproval.sol";
import {SessionKey} from "src/v2/authenticators/types/SessionKey.sol";
import {AuthDelegation} from "src/v2/types/AuthDelegation.sol";
import {ERC20Transfer} from "src/v2/types/ERC20Transfer.sol";
import {ERC721Transfer} from "src/v2/types/ERC721Transfer.sol";
import {ExecutionOrder} from "src/v2/types/ExecutionOrder.sol";
import {ExecutionWitness, PermitBatchWitnessTransferFrom as PermitBatchWitnessTransferFrom_0} from "src/v2/types/ExecutionWitness.sol";
import {FulfillmentOrder} from "src/v2/types/FulfillmentOrder.sol";
import {FulfillmentSolution} from "src/v2/types/FulfillmentSolution.sol";
import {FulfillmentWitness, PermitBatchWitnessTransferFrom as PermitBatchWitnessTransferFrom_1} from "src/v2/types/FulfillmentWitness.sol";
import {GenericCall} from "src/v2/types/GenericCall.sol";
import {NativeTransfer} from "src/v2/types/NativeTransfer.sol";
import {SolutionApproval} from "src/v2/types/SolutionApproval.sol";
import {ValidationParams} from "src/v2/types/ValidationParams.sol";

interface Vm {
    function parseJsonTypeArray(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function serializeJsonType(string calldata typeDescription, bytes memory value) external pure returns (string memory json);
    function serializeJsonType(string calldata objectKey, string calldata valueKey, string calldata typeDescription, bytes memory value) external returns (string memory json);
}
        
library JsonBindings {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    string constant schema_SessionKey = "SessionKey(bytes publicKey,uint8 keyType,uint256 expiration)";
    string constant schema_SessionApproval = "SessionApproval(SessionKey sessionKey,bool approved,uint256 nonce,uint256 deadline)SessionKey(bytes publicKey,uint8 keyType,uint256 expiration)";
    string constant schema_AuthDelegation = "AuthDelegation(address authenticator,bool delegated,bytes data,uint256 nonce,uint256 deadline)";
    string constant schema_ERC20Transfer = "ERC20Transfer(address token,address target,uint160 amount)";
    string constant schema_ERC721Transfer = "ERC721Transfer(address token,uint256 tokenId,address target)";
    string constant schema_NativeTransfer = "NativeTransfer(address target,uint256 amount)";
    string constant schema_GenericCall = "GenericCall(address router,uint256 value,bytes data)";
    string constant schema_ExecutionOrder = "ExecutionOrder(address owner,address relayer,ERC20Transfer[] erc20Transfers,ERC721Transfer[] erc721Transfers,GenericCall[] genericCalls,uint256 nonce,uint256 deadline)ERC20Transfer(address token,address target,uint160 amount)ERC721Transfer(address token,uint256 tokenId,address target)GenericCall(address router,uint256 value,bytes data)";
    string constant schema_ExecutionWitness = "ExecutionWitness(address relayer,address[] erc20Targets,ERC721Transfer[] erc721Transfers,GenericCall[] genericCalls)ERC721Transfer(address token,uint256 tokenId,address target)GenericCall(address router,uint256 value,bytes data)";
    string constant schema_PermitBatchWitnessTransferFrom_0 = "PermitBatchWitnessTransferFrom(TokenPermissions[] permitted,address spender,uint256 nonce,uint256 deadline,ExecutionWitness witness)ERC721Transfer(address token,uint256 tokenId,address target)ExecutionWitness(address relayer,address[] erc20Targets,ERC721Transfer[] erc721Transfers,GenericCall[] genericCalls)GenericCall(address router,uint256 value,bytes data)TokenPermissions(address token,uint256 amount)";
    string constant schema_ValidationParams = "ValidationParams(address validator,bytes32 action,bytes beforeExecutionInput,bytes afterExecutionInput)";
    string constant schema_FulfillmentOrder = "FulfillmentOrder(address owner,address solver,ERC20Transfer[] erc20Transfers,ERC721Transfer[] erc721Transfers,ValidationParams[] validationParams,GenericCall[] ownerCalls,address solutionApprover,uint256 nonce,uint256 deadline)ERC20Transfer(address token,address target,uint160 amount)ERC721Transfer(address token,uint256 tokenId,address target)GenericCall(address router,uint256 value,bytes data)ValidationParams(address validator,bytes32 action,bytes beforeExecutionInput,bytes afterExecutionInput)";
    string constant schema_FulfillmentSolution = "FulfillmentSolution(GenericCall[] solverCalls,uint256 nonce,uint256 deadline)GenericCall(address router,uint256 value,bytes data)";
    string constant schema_FulfillmentWitness = "FulfillmentWitness(address solver,address[] erc20Targets,ERC721Transfer[] erc721Transfers,GenericCall[] ownerCalls,ValidationParams[] validationParams,address callsSigner)ERC721Transfer(address token,uint256 tokenId,address target)GenericCall(address router,uint256 value,bytes data)ValidationParams(address validator,bytes32 action,bytes beforeExecutionInput,bytes afterExecutionInput)";
    string constant schema_PermitBatchWitnessTransferFrom_1 = "PermitBatchWitnessTransferFrom(TokenPermissions[] permitted,address spender,uint256 nonce,uint256 deadline,FulfillmentWitness witness)ERC721Transfer(address token,uint256 tokenId,address target)FulfillmentWitness(address solver,address[] erc20Targets,ERC721Transfer[] erc721Transfers,GenericCall[] ownerCalls,ValidationParams[] validationParams,address callsSigner)GenericCall(address router,uint256 value,bytes data)TokenPermissions(address token,uint256 amount)ValidationParams(address validator,bytes32 action,bytes beforeExecutionInput,bytes afterExecutionInput)";
    string constant schema_SolutionApproval = "SolutionApproval(bytes32 orderHash,FulfillmentSolution solution)FulfillmentSolution(GenericCall[] solverCalls,uint256 nonce,uint256 deadline)GenericCall(address router,uint256 value,bytes data)";

    function serialize(SessionKey memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SessionKey, abi.encode(value));
    }

    function serialize(SessionKey memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SessionKey, abi.encode(value));
    }

    function deserializeSessionKey(string memory json) public pure returns (SessionKey memory) {
        return abi.decode(vm.parseJsonType(json, schema_SessionKey), (SessionKey));
    }

    function deserializeSessionKey(string memory json, string memory path) public pure returns (SessionKey memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SessionKey), (SessionKey));
    }

    function deserializeSessionKeyArray(string memory json, string memory path) public pure returns (SessionKey[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SessionKey), (SessionKey[]));
    }

    function serialize(SessionApproval memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SessionApproval, abi.encode(value));
    }

    function serialize(SessionApproval memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SessionApproval, abi.encode(value));
    }

    function deserializeSessionApproval(string memory json) public pure returns (SessionApproval memory) {
        return abi.decode(vm.parseJsonType(json, schema_SessionApproval), (SessionApproval));
    }

    function deserializeSessionApproval(string memory json, string memory path) public pure returns (SessionApproval memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SessionApproval), (SessionApproval));
    }

    function deserializeSessionApprovalArray(string memory json, string memory path) public pure returns (SessionApproval[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SessionApproval), (SessionApproval[]));
    }

    function serialize(AuthDelegation memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_AuthDelegation, abi.encode(value));
    }

    function serialize(AuthDelegation memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_AuthDelegation, abi.encode(value));
    }

    function deserializeAuthDelegation(string memory json) public pure returns (AuthDelegation memory) {
        return abi.decode(vm.parseJsonType(json, schema_AuthDelegation), (AuthDelegation));
    }

    function deserializeAuthDelegation(string memory json, string memory path) public pure returns (AuthDelegation memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_AuthDelegation), (AuthDelegation));
    }

    function deserializeAuthDelegationArray(string memory json, string memory path) public pure returns (AuthDelegation[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_AuthDelegation), (AuthDelegation[]));
    }

    function serialize(ERC20Transfer memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ERC20Transfer, abi.encode(value));
    }

    function serialize(ERC20Transfer memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ERC20Transfer, abi.encode(value));
    }

    function deserializeERC20Transfer(string memory json) public pure returns (ERC20Transfer memory) {
        return abi.decode(vm.parseJsonType(json, schema_ERC20Transfer), (ERC20Transfer));
    }

    function deserializeERC20Transfer(string memory json, string memory path) public pure returns (ERC20Transfer memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ERC20Transfer), (ERC20Transfer));
    }

    function deserializeERC20TransferArray(string memory json, string memory path) public pure returns (ERC20Transfer[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ERC20Transfer), (ERC20Transfer[]));
    }

    function serialize(ERC721Transfer memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ERC721Transfer, abi.encode(value));
    }

    function serialize(ERC721Transfer memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ERC721Transfer, abi.encode(value));
    }

    function deserializeERC721Transfer(string memory json) public pure returns (ERC721Transfer memory) {
        return abi.decode(vm.parseJsonType(json, schema_ERC721Transfer), (ERC721Transfer));
    }

    function deserializeERC721Transfer(string memory json, string memory path) public pure returns (ERC721Transfer memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ERC721Transfer), (ERC721Transfer));
    }

    function deserializeERC721TransferArray(string memory json, string memory path) public pure returns (ERC721Transfer[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ERC721Transfer), (ERC721Transfer[]));
    }

    function serialize(NativeTransfer memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_NativeTransfer, abi.encode(value));
    }

    function serialize(NativeTransfer memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_NativeTransfer, abi.encode(value));
    }

    function deserializeNativeTransfer(string memory json) public pure returns (NativeTransfer memory) {
        return abi.decode(vm.parseJsonType(json, schema_NativeTransfer), (NativeTransfer));
    }

    function deserializeNativeTransfer(string memory json, string memory path) public pure returns (NativeTransfer memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_NativeTransfer), (NativeTransfer));
    }

    function deserializeNativeTransferArray(string memory json, string memory path) public pure returns (NativeTransfer[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_NativeTransfer), (NativeTransfer[]));
    }

    function serialize(GenericCall memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_GenericCall, abi.encode(value));
    }

    function serialize(GenericCall memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_GenericCall, abi.encode(value));
    }

    function deserializeGenericCall(string memory json) public pure returns (GenericCall memory) {
        return abi.decode(vm.parseJsonType(json, schema_GenericCall), (GenericCall));
    }

    function deserializeGenericCall(string memory json, string memory path) public pure returns (GenericCall memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_GenericCall), (GenericCall));
    }

    function deserializeGenericCallArray(string memory json, string memory path) public pure returns (GenericCall[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_GenericCall), (GenericCall[]));
    }

    function serialize(ExecutionOrder memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ExecutionOrder, abi.encode(value));
    }

    function serialize(ExecutionOrder memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ExecutionOrder, abi.encode(value));
    }

    function deserializeExecutionOrder(string memory json) public pure returns (ExecutionOrder memory) {
        return abi.decode(vm.parseJsonType(json, schema_ExecutionOrder), (ExecutionOrder));
    }

    function deserializeExecutionOrder(string memory json, string memory path) public pure returns (ExecutionOrder memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ExecutionOrder), (ExecutionOrder));
    }

    function deserializeExecutionOrderArray(string memory json, string memory path) public pure returns (ExecutionOrder[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ExecutionOrder), (ExecutionOrder[]));
    }

    function serialize(ExecutionWitness memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ExecutionWitness, abi.encode(value));
    }

    function serialize(ExecutionWitness memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ExecutionWitness, abi.encode(value));
    }

    function deserializeExecutionWitness(string memory json) public pure returns (ExecutionWitness memory) {
        return abi.decode(vm.parseJsonType(json, schema_ExecutionWitness), (ExecutionWitness));
    }

    function deserializeExecutionWitness(string memory json, string memory path) public pure returns (ExecutionWitness memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ExecutionWitness), (ExecutionWitness));
    }

    function deserializeExecutionWitnessArray(string memory json, string memory path) public pure returns (ExecutionWitness[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ExecutionWitness), (ExecutionWitness[]));
    }

    function serialize(PermitBatchWitnessTransferFrom_0 memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_PermitBatchWitnessTransferFrom_0, abi.encode(value));
    }

    function serialize(PermitBatchWitnessTransferFrom_0 memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_PermitBatchWitnessTransferFrom_0, abi.encode(value));
    }

    function deserializePermitBatchWitnessTransferFrom_0(string memory json) public pure returns (PermitBatchWitnessTransferFrom_0 memory) {
        return abi.decode(vm.parseJsonType(json, schema_PermitBatchWitnessTransferFrom_0), (PermitBatchWitnessTransferFrom_0));
    }

    function deserializePermitBatchWitnessTransferFrom_0(string memory json, string memory path) public pure returns (PermitBatchWitnessTransferFrom_0 memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_PermitBatchWitnessTransferFrom_0), (PermitBatchWitnessTransferFrom_0));
    }

    function deserializePermitBatchWitnessTransferFrom_0Array(string memory json, string memory path) public pure returns (PermitBatchWitnessTransferFrom_0[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_PermitBatchWitnessTransferFrom_0), (PermitBatchWitnessTransferFrom_0[]));
    }

    function serialize(ValidationParams memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ValidationParams, abi.encode(value));
    }

    function serialize(ValidationParams memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ValidationParams, abi.encode(value));
    }

    function deserializeValidationParams(string memory json) public pure returns (ValidationParams memory) {
        return abi.decode(vm.parseJsonType(json, schema_ValidationParams), (ValidationParams));
    }

    function deserializeValidationParams(string memory json, string memory path) public pure returns (ValidationParams memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ValidationParams), (ValidationParams));
    }

    function deserializeValidationParamsArray(string memory json, string memory path) public pure returns (ValidationParams[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ValidationParams), (ValidationParams[]));
    }

    function serialize(FulfillmentOrder memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_FulfillmentOrder, abi.encode(value));
    }

    function serialize(FulfillmentOrder memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_FulfillmentOrder, abi.encode(value));
    }

    function deserializeFulfillmentOrder(string memory json) public pure returns (FulfillmentOrder memory) {
        return abi.decode(vm.parseJsonType(json, schema_FulfillmentOrder), (FulfillmentOrder));
    }

    function deserializeFulfillmentOrder(string memory json, string memory path) public pure returns (FulfillmentOrder memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_FulfillmentOrder), (FulfillmentOrder));
    }

    function deserializeFulfillmentOrderArray(string memory json, string memory path) public pure returns (FulfillmentOrder[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_FulfillmentOrder), (FulfillmentOrder[]));
    }

    function serialize(FulfillmentSolution memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_FulfillmentSolution, abi.encode(value));
    }

    function serialize(FulfillmentSolution memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_FulfillmentSolution, abi.encode(value));
    }

    function deserializeFulfillmentSolution(string memory json) public pure returns (FulfillmentSolution memory) {
        return abi.decode(vm.parseJsonType(json, schema_FulfillmentSolution), (FulfillmentSolution));
    }

    function deserializeFulfillmentSolution(string memory json, string memory path) public pure returns (FulfillmentSolution memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_FulfillmentSolution), (FulfillmentSolution));
    }

    function deserializeFulfillmentSolutionArray(string memory json, string memory path) public pure returns (FulfillmentSolution[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_FulfillmentSolution), (FulfillmentSolution[]));
    }

    function serialize(FulfillmentWitness memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_FulfillmentWitness, abi.encode(value));
    }

    function serialize(FulfillmentWitness memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_FulfillmentWitness, abi.encode(value));
    }

    function deserializeFulfillmentWitness(string memory json) public pure returns (FulfillmentWitness memory) {
        return abi.decode(vm.parseJsonType(json, schema_FulfillmentWitness), (FulfillmentWitness));
    }

    function deserializeFulfillmentWitness(string memory json, string memory path) public pure returns (FulfillmentWitness memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_FulfillmentWitness), (FulfillmentWitness));
    }

    function deserializeFulfillmentWitnessArray(string memory json, string memory path) public pure returns (FulfillmentWitness[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_FulfillmentWitness), (FulfillmentWitness[]));
    }

    function serialize(PermitBatchWitnessTransferFrom_1 memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_PermitBatchWitnessTransferFrom_1, abi.encode(value));
    }

    function serialize(PermitBatchWitnessTransferFrom_1 memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_PermitBatchWitnessTransferFrom_1, abi.encode(value));
    }

    function deserializePermitBatchWitnessTransferFrom_1(string memory json) public pure returns (PermitBatchWitnessTransferFrom_1 memory) {
        return abi.decode(vm.parseJsonType(json, schema_PermitBatchWitnessTransferFrom_1), (PermitBatchWitnessTransferFrom_1));
    }

    function deserializePermitBatchWitnessTransferFrom_1(string memory json, string memory path) public pure returns (PermitBatchWitnessTransferFrom_1 memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_PermitBatchWitnessTransferFrom_1), (PermitBatchWitnessTransferFrom_1));
    }

    function deserializePermitBatchWitnessTransferFrom_1Array(string memory json, string memory path) public pure returns (PermitBatchWitnessTransferFrom_1[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_PermitBatchWitnessTransferFrom_1), (PermitBatchWitnessTransferFrom_1[]));
    }

    function serialize(SolutionApproval memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SolutionApproval, abi.encode(value));
    }

    function serialize(SolutionApproval memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SolutionApproval, abi.encode(value));
    }

    function deserializeSolutionApproval(string memory json) public pure returns (SolutionApproval memory) {
        return abi.decode(vm.parseJsonType(json, schema_SolutionApproval), (SolutionApproval));
    }

    function deserializeSolutionApproval(string memory json, string memory path) public pure returns (SolutionApproval memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SolutionApproval), (SolutionApproval));
    }

    function deserializeSolutionApprovalArray(string memory json, string memory path) public pure returns (SolutionApproval[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SolutionApproval), (SolutionApproval[]));
    }
}
